### ISSUE TITLE
What is difference between text and heading?

### ISSUE THREAD

**Issue by iamrishishah** [modulz/prototype-feedback#17]
![image](https://user-images.githubusercontent.com/49694573/103198751-25a77280-490f-11eb-939a-7f66e61e4cd7.png)

I couldn't see any difference in the property panel when I was selecting the type and heading. If users are already able to create heading with text function so why do they need to add the heading function in their design. I couldn't find any specific reason which encouraged me to use heading. Sometimes delivering less options gives.

Currently, I am not aware of your plan with the heading function but as per current usage, I feel it's an unnecessary function for the user.

**Comment by royalicing** [comment]
Heading has semantic meaning, especially in HTML and accessibility. So it probably makes sense that it's its own component.

**Comment by StephenHaney** [comment]
Thanks for this one! We'll discuss internally on the best way to handle this and explain it to the user. Feel free to reopen if you have additional thoughts.

**Comment by iamrishishah** [comment]
I think there should have an option in  property panel to switch the paragraph in to heading and vice versa.
