### ISSUE TITLE
Icons / SVG support

### ISSUE THREAD

**Issue by cdes** [modulz/prototype-feedback#19]
**Is your feature request related to a problem? Please describe.**
Since Modulz now doesn't have Icons... I'm using the image component.  SVG inside img can't accept a color (e.g. using currentColor.  I'm using https://yoksel.github.io/url-encoder/ to encode SVG as CSS backgrounds.

**Describe the solution you'd like**
I want the ability to upload SVGs as components

**Describe alternatives you've considered**
use Radix icons

**Additional context**
I like how Figma understands SVG, so whenever you copy SVG source from somewhere and paste it in Figma, it will just insert it as if you have dragged the SVG into Figma.

**Comment by StephenHaney** [comment]
Thanks for the feedback! SVG pasting support is definitely planned and should be supported within the next month or two.

We'll support pasting the actual SVG data as text and SVG files.

**Comment by StephenHaney** [comment]
Going to close this as we're tracking it internally. The next release includes SVG support, although not the ability to apply styles. The following release (May 1st-ish) will allow you to apply styles to SVGs.
