### ISSUE TITLE
Limit children in Text

### ISSUE THREAD

**Issue by souporserious** [modulz/prototype-feedback#2]
Currently it looks like anything can be nested inside Text. Should there only be the ability to nest Text elements within each other?

**Comment by StephenHaney** [comment]
Yes! Nesting validation is one of those "haven't even started it yet" items. Right now you can put Buttons in Buttons too 😨

**Comment by souporserious** [comment]
Ah awesome, good to know! 😆

**Comment by StephenHaney** [comment]
Going to close this one as it'll be on the roadmap and you'll see it ship in our updates.

Just let me know if you have any ideas or feature requests around it! Thanks for bringing it up.
