### ISSUE TITLE
Couldn't Login - You don't have access just yet.

### ISSUE THREAD

**Issue by iamrishishah** [modulz/prototype-feedback#22]
![image](https://user-images.githubusercontent.com/49694573/107732399-42143880-6d1e-11eb-892e-a4a49787ffdf.png)

**Comment by StephenHaney** [comment]
Sorry about this. Just to double check, you used the link in the email to set a new password, then tried to log in using the email address that we sent the invite to and your new password? I see your account as active. I'll shoot you an email to the gmail address ending in '92'.

Closing this and we'll continue in email.

**Comment by iamrishishah** [comment]
I think you need to add a logout button on this screen so the user can at least retry after some time. I know we can clear cache files or use private mode to re-try but many of your users wouldn't like to clear their catch files or browser history.

**Comment by StephenHaney** [comment]
Thanks Rishi, good idea. Were you able to log in successfully now?

CC @ssskram

**Comment by iamrishishah** [comment]
Yes, @StephenHaney now I am able to access it. Thanks
