### ISSUE TITLE
Flex walkthrough behavior doesn't match instructions

### ISSUE THREAD

**Issue by mattaningram** [modulz/prototype-feedback#26]
**Describe the bug**
In the Welcome to Modulz file flex walkthrough, the box with two buttons in it doesn't show the buttons stacked the way the gif that appears shows because the buttons default to `inline-flex`. So setting the box to flex row doesn't make any visual change.

**To Reproduce**
1. Go to 'Welcome to Modulz' file
2. Follow the Real (auto)layout steps
3. Add two buttons to box as asked
4. See that buttons appear inline and not stacked the way the gif suggests they will appear

**Expected behavior**
Either buttons should default to regular `flex` so they stack, or the prototype instructions should be updated to reflect new default behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/955092/120669987-f8329800-c45d-11eb-8d26-55029a01628e.png)

**Desktop**
 - OS: [macOS]
 - Browser [Chrome v91]

**Comment by StephenHaney** [comment]
Thanks for this — planning to revamp the tutorial soon so it missed out on a polish round for this release. I'll make sure we clean it up.
