### ISSUE TITLE
Vector preview in layers list is affected by 'position: absolute'

### ISSUE THREAD

**Issue by cdes** [modulz/prototype-feedback#28]
**Describe the bug**
Vector preview in layers list is affected by `position: absolute`

https://user-images.githubusercontent.com/1207863/122004301-e980a500-cdbc-11eb-931c-ea3c47198be0.mov

**To Reproduce**
1. Drag an SVG to Modulz
2. Enable Position property
3. Select "Absolute" or "Fixed"
4. See error.

**Expected behavior**
The preview to stay the same.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version Catalina 10.15.7

**Comment by StephenHaney** [comment]
That's a fun one. We'll fix it up. Thanks for the report!
