### ISSUE TITLE
SVG vectors appear in canvas but not in preview

### ISSUE THREAD

**Issue by cdes** [modulz/prototype-feedback#29]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1207863/122019597-9f9fbb00-cdcc-11eb-9629-d973a6ded8df.png)
SVG vectors appear in canvas but not in preview

**To Reproduce**
1. Copy any SVG vector 
2. Paste in Modulz
3. Click Preview

**Expected behavior**
The vector should appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 Catalina
 - Browser Chrome
 - Version 91.0.4472.77

**Additional context**
```
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  preserveAspectRatio="none"
  color="#1B254A"
  style="boxSizing: border-box;height: 24px;verticalAlign: top;width: 24px;bottom: auto;left: auto;position: absolute;right: 20px;top: 48px;transform: none;"
>
  <path
    d="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12L19 6.41Z"
    fill="currentColor"
  />
</svg>
```

**Comment by StephenHaney** [comment]
Investigating. Thanks for the thorough repro!

**Comment by hadihallak** [comment]
Salaam @cdes 👋 

This is now fixed and will be part of the next release. 
Please keep the feedback coming and don't hesitate to reach out if you have any questions or suggestions.

**Comment by hadihallak** [comment]
The fix for this bug is live. thanks for reporting the issue 🙏

**Comment by cdes** [comment]
It works, awesome!

![image](https://user-images.githubusercontent.com/1207863/124498709-75d32600-ddc5-11eb-8f9f-79e0b2d98fa1.png)
