### ISSUE TITLE
Support input props (placeholder, value)

### ISSUE THREAD

**Issue by cdes** [modulz/prototype-feedback#30]
**Is your feature request related to a problem? Please describe.**
It's really annoying to not be able to add a placeholder for input.
For example, I'm designing a search field, and I want to add "Search" as a placeholder.

**Describe the solution you'd like**
Allow me to edit placeholder in properties panel.

**Describe alternatives you've considered**
Adding a positioned text is just weird.

**Comment by StephenHaney** [comment]
Yes, definitely. When we add props support we will also add placeholder and other useful attributes in the right panels. Thank you for the report.
