### ISSUE TITLE
Support button & input states

### ISSUE THREAD

**Issue by cdes** [modulz/prototype-feedback#31]
**Is your feature request related to a problem? Please describe.**
I can't set the hover, active and focused styles.

**Describe the solution you'd like**
I would like to toggle between states and customize these styles.

**Describe alternatives you've considered**
I have to add custom css which is counter-intuitive.

**Additional context**
I know you have this on the roadmap, but I wanted to point it out because it's important.

**Comment by StephenHaney** [comment]
That's awesome, thanks for the +1 for states. Right now we're focusing on layout and trying to make the canvas experience feel great, but states is a very necessary feature and on the roadmap, as you note.

Going to close this issue to help myself stay organized, but I will keep the feedback in mind.
