### ISSUE TITLE
Welcome Tutorial first step could use some clarity

### ISSUE THREAD

**Issue by six7** [modulz/prototype-feedback#4]
Not really a bug but I was kind of confused on the first step of the tutorial, which in hindsight should've been pretty clear:

- Instead of dragging the whole card I was only dragging a single text element out and thought the tutorial was broken as nothing happened (as I was able to see all the layers on the left but they had 0x0 size). I guess I was taking the "Can you drag **me** out of this artboard please?" too literal 😅

- Later moved the whole card out of the artboard and the tutorial went on as intended.

**Comment by StephenHaney** [comment]
Oh, interesting! The card should be grouped so you'd have to double click to select the text, right?

I'll change the copy to "this card", good feedback.

**Comment by six7** [comment]
Right! In hindsight I have no clue why I decided to drill down and move the text layer 😅

**Comment by StephenHaney** [comment]
This has been updated and will update on the server the next time the tutorial has nobody in it. 👍
