### ISSUE TITLE
Fails for browsers with WebGL turned off (and no visible warning)

### ISSUE THREAD

**Issue by iamrishishah** [modulz/prototype-feedback#8]
My internet speed is 39.2 Mbps download speed and I use the opera 72.0.3815.400 and Chrome 87.0.4280.88

It can be better if I know how much time it will take or to know the progress of loading. Because I am just stay on the screen for 2-3 mins and noting happens. 

It's really disappointed experience for newly onboarded users.

**Comment by colmtuite** [comment]
Sorry you had a bad experience with loading.

Unfortunately, we don't have the capacity right now to optimise the product for outdated browsers like Opera.

Next year, we will begin optimising browser compatibility. For now, we recommend using Chrome.

I know you tried Chrome too, we will look into this issue. Thanks

**Comment by StephenHaney** [comment]
Hey — mind trying with any adblockers turned off and see if you get a different result?

If you see loading for more than a second or two, something's gone wrong.

I took a look at some of the errors and it looks like "This browser doesn't support webGL" is popping up a lot. Is that something you have disabled?

**Comment by iamrishishah** [comment]
I opened up in incognito mode and allowed third party cookies but still it doesn't work. 

![image](https://user-images.githubusercontent.com/49694573/102966326-afbd9880-4515-11eb-9927-ebae58abb234.png)
.

**Comment by StephenHaney** [comment]
Hmm, yeah, still seeing `Error: This browser does not support WebGL.` in our logs from that session. This is something new, I'll need to look into it to see if there are options for when WebGL isn't supported. Sorry you ran into this. I'll update this issue when we know more.

**Comment by iamrishishah** [comment]
Yes you right. I also get the WebGL error from the Figma. It can be better if you display this kind of error which educate the users. 

![image](https://user-images.githubusercontent.com/49694573/102993012-6b94bd00-4542-11eb-90af-861b582a839f.png)

**Comment by StephenHaney** [comment]
Definitely, I will add something like that to our list. We might be able to fall back to canvas to do the rendering we need too so people with WebGL turned off can still use Modulz.

Did you disable WebGL off on purpose or is it a hardware thing?

**Comment by iamrishishah** [comment]
It works well after restarting the system.

**Comment by StephenHaney** [comment]
Thanks again for reporting this, we're shipping a warning for users with webGL disabled in the next release so they don't just get "Loading..." forever.
